### ISSUE TITLE
Map Server Crash in skill_unit_timer_sub

### ISSUE THREAD

**Issue by inhyositsu** [HerculesWS/Hercules#1299]
group is strange (0xfdfdfdfdfdfdfdfd)
and make map-server crash.

```
#0  skill_unit_timer_sub (key=..., data=<optimized out>, ap=<optimized out>)
    at skill.c:16572
        su = 0x7f7627070b94
        group = 0xfdfdfdfdfdfdfdfd
        tick = 433089499
        dissonance = <optimized out>
        bl = 0x7f7627070b94
        __func__ = "skill_unit_timer_sub"
#1  0x000000000061c87c in db_obj_vforeach (self=0x19a64b8,
    func=0x5a2c20 <skill_unit_timer_sub>, args=0x7ffcd05de3d8) at db.c:2069
        argscopy = {{gp_offset = 24, fp_offset = 48,
            overflow_arg_area = 0x7ffcd05de4b0,
            reg_save_area = 0x7ffcd05de3f0}}
        db = 0x19a64b8
        sum = 0
        node = 0x1002c3f8
        parent = <optimized out>
#2  0x000000000061b823 in db_obj_foreach (self=<optimized out>,
    func=<optimized out>) at db.c:2116
        args = {{gp_offset = 16, fp_offset = 48,
            overflow_arg_area = 0x7ffcd05de4b0,
            reg_save_area = 0x7ffcd05de3f0}}
#3  0x000000000059fbfe in skill_unit_timer (tid=<optimized out>,
    tick=433089499, id=<optimized out>, data=<optimized out>) at skill.c:16775
No locals.
#4  0x0000000000628f2a in do_timer (tick=433089499) at timer.c:489
        tid = 12
        diff = 0
        __func__ = "do_timer"
#5  0x000000000043d70b in main (argc=1, argv=0x7ffcd05de638) at core.c:464
        next = <optimized out>
        retval = 0
```

**Comment by dastgir** [comment]
@4144 @MishimaHaruna
