### ISSUE TITLE
Gloom under night skill server crash

### ISSUE THREAD

**Issue by datleeroy** [HerculesWS/Hercules#1346]
the mvp gloom under night youse a skill and the map server get down
sorry for my bad englisch
#0  0x00000000005589ab in skill_cell_overlap (bl=0x7fffee690bac,

```
ap=ap@entry=0x7fffffffdef8) at skill.c:15272
    skill_id = 19968
    alive = 0x0
    su = 0x7fffee690bac
```
#1  0x00000000004c44be in bl_vforeach (

```
func=func@entry=0x558960 <skill_cell_overlap>,
blockcount=blockcount@entry=0, max=max@entry=2147483647,
args=args@entry=0x7fffffffdf68) at map.c:491
    argscopy = {{gp_offset = 48, fp_offset = 48,
        overflow_arg_area = 0x7fffffffe088,
        reg_save_area = 0x7fffffffdfc0}}
    i = 0
    returnCount = 0
```
#2  0x00000000004cd45f in map_vforeachincell (

```
func=0x558960 <skill_cell_overlap>, m=<optimized out>, x=<optimized out>,
y=<optimized out>, type=<optimized out>, ap=0x7fffffffdfa8) at map.c:1127
    returnCount = 0
    blockcount = 0
    apcopy = {{gp_offset = 40, fp_offset = 48,
        overflow_arg_area = 0x7fffffffe080,
        reg_save_area = 0x7fffffffdfc0}}
```
#3  0x00000000004c3f3c in map_foreachincell (func=<optimized out>,

**Comment by NaiveVisionary** [comment]
What client are you using? Using 2013-08-07 client I don't get an error from any skills gloom under night uses.
