### ISSUE TITLE
@cvcon crash

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1971]
-  [x ] I have not modified the source prior to reproducing this issue.
-  [x ] I am using the latest version of Hercules.
-  [x ] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

Hercules: using latest build
Client: 20151029

Type @cvcon and it will crash
```
Program received signal SIGSEGV, Segmentation fault.
map_zone_change2 (m=171, zone=0x0) at map.c:4515
4515            if( zone->merge_type == MZMT_MERGEABLE && map->list[m].prev_zone->merge_type != MZMT_NEVERMERGE ) {
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64 libgcc-4.8.5-16.el7_4.1.x86_64 libstdc++-4.8.5-16.el7_4.1.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64

#0  map_zone_change2 (m=171, zone=0x0) at map.c:4515
No locals.
#1  0x000000000043bba7 in atcommand_cvcon (fd=11, sd=0x66ab490,
    command=0xa0eb40 <map_s> "", message=0x2394fe4 "Towns", info=0x3c)
    at atcommand.c:1709
No locals.
#2  0x000000000045d395 in atcommand_exec (fd=11, sd=0x66ab490,
    message=0x7fffffffdd18 "@cvcon", player_invoked=228) at atcommand.c:10203
        params = '\000' <repeats 99 times>
        command = "@cvcon", '\000' <repeats 93 times>
        output = "\000\000\000\000\000\000\000\000P\332\377\377\377\177\000\000`\334\377\377\377\177\000\000l\233\067\002\000\000\000\000\304\063/\366\377\177\000\000x\333\377\377\377\177\000\000P\374\371\364\377\177\000\000\000\000\000\000\000\000\000\000`\334\377\377\377\177\000\000\253J\221\366\377\177\000\000\001\200\255\373\000\000\000\000`\334\377\377\377\177\000\000`\334\377\377\377\177\000\000`\334\377\377\377\177\000\000`\334\377\377\377\177\000\000\217\334\377\377\377\177\000\000\377\377\377\377\377\377\377\377`\334\377\377\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 40 times>, "\001\335\377\377", '\000' <repeats 59 times>
        atcmd_msg = "@cvcon\000\000\021\000\000\000\000\000\000\000\377\377\377\377'", '\000' <repeats 19 times>, "\360I\002\000\000\000\000\000\070\001\000\000\000\000\000\000\021\000\000\000\031\000\000\000\000\000\000\000\063\070\066\065P\374\371\364\377\177\000\000\070 \000\000\000\000\000\000\220\333\377\377\377\1---Type <return> to continue, or q <return> to quit---
#3  0x000000000055df52 in pc_process_chat_message (sd=0x66ab490, message=0x0)
    at pc.c:11949
No locals.
#4  0x000000000049c66f in clif_process_chat_message (sd=0x66ab490,
    packet=0x7ffff631c774, out_buf=0x3c <Address 0x3c out of bounds>,
    out_buflen=37310436) at clif.c:9281
        srcname = 0x7ffff631c778 "admin : @cvcon\001"
        message = 0x7fffffffdd18 "@cvcon"
        textlen = -184943536
        __func__ = "clif_process_chat_message"
#5  0x00000000004994d3 in clif_parse_GlobalMessage (fd=11, sd=0x66ab490)
    at clif.c:10145
        full_message = "admin : @cvcon\000\000\000\000\000\000\000\000\000\000\362\016\312\023\000\000\000\000\n\251\312\023\000\000\000\000@\353\240\000\000\000\000\000\300\335\377\377\377\177\000\000\350\335\377\377\377\177\000\000P\372\\", '\000' <repeats 13 times>, "\274\002\000\000\000\000\000\000ާ\312\023\000\000\000\000\320\335\377\377", '\000' <repeats 20 times>, "\330\b\000\000\000\000\0---Type <return> to continue, or q <return> to quit---
#6  0x00000000004922c2 in clif_parse (fd=11) at clif.c:20222
        parse_cmd_func = 0x7ffff4f9fc50
        packet_len = 10545984
        sd = 0x66ab490
#7  0x000000000065eb0e in do_sockets (next=88) at socket.c:1026
        rfd = {fds_bits = {2048, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 52537}
        ret = 0
#8  0x000000000043a842 in main (argc=1, argv=0x7fffffffe088) at core.c:560
        next = -184943536
        retval = 6642112
```

**Comment by 4144** [comment]
this error look like mean you have outdated map zones file.
but anyway server should not crash.

**Comment by 4144** [comment]
try this pull request: https://github.com/HerculesWS/Hercules/pull/1972
